In [4]:
import numpy as np
import pandas as pd
from IPython.display import display

In [7]:
df = pd.read_csv('tips.csv')

display(df)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [16]:
df = pd.read_csv('tips.csv')
df.sort_values('tip')
df.sort_values(by=['tip', 'size'], ascending=[True, False])

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
...,...,...,...,...,...,...,...,...,...,...,...
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954

In [27]:
############################## how many smokers? how many male/female smokers?
df = pd.read_csv('tips.csv')
print(df['smoker'].value_counts())  # groupby + count(*)
# count how many rows for each day
# count how many male/ female 
# ? count how many male-smoker and female non-smokers
display(df[['sex', 'smoker']].value_counts())
display(df[['sex', 'smoker']].value_counts()['Female']['No'])
print(df[['sex', 'smoker']].value_counts()[('Male', 'Yes')])

smoker
No     151
Yes     93
Name: count, dtype: int64

sex     smoker
Male    No        97
        Yes       60
Female  No        54
        Yes       33
Name: count, dtype: int64

54

60

In [30]:
df = pd.read_csv('tips.csv')
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [79]:
############################## which values do i have in this column? how many diff values I have?
df = pd.read_csv('tips.csv')
df['day'].unique()  # sql -> distinct, no dup
display(df['size'].unique())
print(100 in df['size'].values)  # fastest !!
print(3 in df['size'].unique())  # worse ..
df['size'].isin([100]).any()  # also not fast

df = df.set_index('day')
# df[(df.index == 'Sun') & (df['size'] == 2)]
df['size'].isin([3]).any()

print(len( df['size'].unique()))
df['size'].nunique()  # count(*) for distinct

array([2, 3, 4, 1, 6, 5], dtype=int64)

False
True
6

6

In [83]:
df = pd.read_csv('tips.csv')
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [94]:
############################## how to replcace values
df = pd.read_csv('tips.csv')

# 1 -- replace, can modify part of the values, i.e.
df['sex'] = df['sex'].replace(['Female'],['F'])

# 2 -- map -- more readable, must include ALL values 
gender_map = { 'Female': 'F', 'Male': 'Male' }
df['sex'] = df['sex'].map(gender_map)
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,F,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,F,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,F,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,F,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [97]:
df = pd.read_csv('tips.csv')
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [110]:
df = pd.read_csv('tips.csv')

########### how to get 3 rows of most expensive/cheapest?
# 1
df.sort_values(['total_bill'], ascending=False).head(3)

# 2 - faster 
df.nlargest(3, 'total_bill')
df.nsmallest(3, 'total_bill')

######### how to get 3 random rows
df.sample(5)            # 5 random rows
df.sample(frac = 0.01)  # 1% random

# get the 3 most largest tips 
# get the unqiue "Payer Name" of the people that gave the 5 largest tips (no duplications)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
83,32.68,5.0,Male,Yes,Thur,Lunch,2,16.34,Daniel Murphy,5356177501009133,Thur8801
132,11.17,1.5,Female,No,Thur,Lunch,2,5.58,Taylor Gonzalez,6011990685390011,Thur7783

In [ ]:
################ How to Clean data ?
## 1 duplication
## 2 missing values - keep or not? what to do with missing value? NaN is NOT always a solution
##                    NaN -> 0, NaN -> random_value (range min-max), NaN -> min/max, NaN -> mean

In [124]:
simple_df = pd.DataFrame([1, 2, 2, 2], ['a', 'b', 'c', 'd'])
simple_df

# which row is a duplication
display(simple_df)
display(simple_df.duplicated())

simple_df[~simple_df.duplicated()]  # get rows without duplication
display(simple_df.drop_duplicates(keep='last')) # get rows without duplicationsame but shorter
display(simple_df.drop_duplicates(keep='first')) # get rows without duplicationsame but shorter
display(simple_df.drop_duplicates(keep=False)) # get rows without duplicationsame but shorter

   0
a  1
b  2
c  2
d  2

a    False
b    False
c     True
d     True
dtype: bool

   0
a  1
d  2

   0
a  1
b  2

   0
a  1

In [140]:
df = pd.read_csv('tips.csv')
# df[~df['size'].duplicated()]

# how to get only 1 from each size but with the highest tip of this group ?
# display(df.sort_values(by=['size', 'tip'], ascending=[True, False]))
# 1
df_sorted = df.sort_values(by=['size', 'tip'], ascending=[True, False])
df_sorted[~df_sorted['size'].duplicated(keep='first')]  # <-- bad, because the is command drop_duplicates('size') 

# 2
df.sort_values(by=['size', 'tip'], ascending=[True, False]).drop_duplicates('size')  # <-- correct

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
222,8.58,1.92,Male,Yes,Fri,Lunch,1,8.58,Jason Lawrence,3505302934650403,Fri6624
88,24.71,5.85,Male,No,Thur,Lunch,2,12.36,Roger Taylor,4410248629955,Thur9003
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590
155,29.85,5.14,Female,No,Sun,Dinner,5,5.97,Madison Wilson,4210875236164664,Sun9176
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025

In [141]:
#### missing data 
df = pd.read_csv('movie_scores.csv')
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [146]:
import math
x = np.nan
print(x == np.nan)  # IEEE 754 NaN is explicitly defined to never equal anything, including itself
print(x is np.nan)
print(np.isnan(x))
print(math.isnan(x))

False
True
True
True

In [154]:
#### missing data 
df = pd.read_csv('movie_scores.csv')
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [176]:
#### missing data - identify and manual remove
df = pd.read_csv('movie_scores.csv')
df.isna()
df[~df['first_name'].isna()]    # 1 - get all rows which have first_name
df[df['first_name'].notnull()]  # 2 - better
df[df['pre_movie_score'].notnull() & df['post_movie_score'].notnull()]

0    False
1     True
2     True
3    False
4    False
dtype: bool

In [171]:
#### missing data - identify and manual remove
df = pd.read_csv('movie_scores.csv')
df.dropna()  # <-- remove all rows which have even 1 NaN inside!
df.dropna(thresh=5)  # <-- keep all rows which have at least 5 columns with VALUES inside

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [177]:
#### missing data - 
df = pd.read_csv('movie_scores.csv')
df.dropna(subset=['first_name', 'pre_movie_score'])  # remove all rows which have NaN in first_name OR pre_movie_score

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [188]:
#### missing data - replace using fillna
df = pd.read_csv('movie_scores.csv')

# 1 manually
df['pre_movie_score'] = df['pre_movie_score'].replace(np.nan, 0)  # manually

# better 
df['pre_movie_score'] = df['pre_movie_score'].fillna(0)  # better

# replace with mean
df['pre_movie_score'] = df['pre_movie_score'].fillna(df['pre_movie_score'].mean())  # better
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              0.0               NaN
2       Hugh   Jackman  51.0    m              0.0               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0